robot:
  schunk_arm_controller:
    type: effort_controllers/JointTrajectoryController

    joints:
        - arm_1_joint
        - arm_2_joint
        - arm_3_joint
        - arm_4_joint
        - arm_5_joint
        - arm_6_joint

    gains:
        arm_1_joint: {p:  500.0, d: 50.0}
        arm_2_joint: {p:  800.0, d: 50.0}
        arm_3_joint: {p:  350.0, d: 30.0}
        arm_4_joint: {p:  300.0, d:  3.0}
        arm_5_joint: {p:  500.0, d:  3.0}
        arm_6_joint: {p:  10.0, d: 3.0}

    constraints:
        goal_time: 5.0
        arm_1_joint:
            goal: 0.05
            trajectory: 0.10
        arm_2_joint:
            goal: 0.05
            trajectory: 0.10
        arm_3_joint:
            goal: 0.05
            trajectory: 0.10
        arm_4_joint:
            goal: 0.05
            trajectory: 0.10
        arm_5_joint:
            goal: 0.05
            trajectory: 0.10
        arm_6_joint:
            goal: 0.05
            trajectory: 0.10

  schunk_gripper_controller:
    type: effort_controllers/JointTrajectoryController

    joints:
        - wsg_50_finger_left_joint
        - wsg_50_finger_right_joint

    gains:
        wsg_50_finger_left_joint: {p: 10.0, d: 3.0}
        wsg_50_finger_right_joint: {p: 10.0, d: 3.0}
