robot:
  schunk_arm_controller:
    type: effort_controllers/JointTrajectoryController

    joints:
        - arm_1_joint
        - arm_2_joint
        - arm_3_joint
        - arm_4_joint
        - arm_5_joint
        - arm_6_joint

    gains:
        arm_1_joint: {p: 100.0, i: 0.01, d: 10.0}
        arm_2_joint: {p: 100.0, i: 0.01, d: 10.0}
        arm_3_joint: {p: 100.0, i: 0.01, d: 10.0}
        arm_4_joint: {p: 100.0, i: 0.01, d: 10.0}
        arm_5_joint: {p: 200.0, i: 0.01, d: 10.0}
        arm_6_joint: {p: 50.0, i: 0.01, d: 3.0}
        #arm_1_joint: {p:  180.0, d: 20.0}
        #arm_2_joint: {p:  220.0, d: 25.0}
        #arm_3_joint: {p:  50.0, d: 10.0}
        #arm_4_joint: {p:  60.0, d: 4.0}
        #arm_5_joint: {p:  70.0, d: 2.0}
        #arm_6_joint: {p:  80.0, d: 2.0}

    constraints:
        goal_time: 120.0
        arm_1_joint:
            goal: 0.5
            #trajectory: 0.10
        arm_2_joint:
            goal: 0.5
        #    trajectory: 0.10
        arm_3_joint:
            goal: 0.5
        #    trajectory: 0.10
        arm_4_joint:
            goal: 0.5
        #    trajectory: 0.10
        arm_5_joint:
            goal: 0.5
        #    trajectory: 0.10
        arm_6_joint:
            goal: 0.5
        #    trajectory: 0.10

  schunk_gripper_controller:
    type: effort_controllers/JointTrajectoryController

    joints:
        - wsg_50_base_joint_gripper_left
        - wsg_50_base_joint_gripper_right

    #dependent_joints:
        #wsg_50_base_joint_gripper_left: {parent: wsg_50_base_joint_gripper_right, factor: -1 }

    gains:
        wsg_50_base_joint_gripper_left: {p: 50.0, d: 3.0}
        wsg_50_base_joint_gripper_right: {p: 50.0, d: 3.0}
