robot:
    ## joint_names
  #joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, wsg_50_base_joint_gripper_left, wsg_50_base_joint_gripper_right]

    ## joint_state_controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_1_joint_effort_controller:
    type: effort_controllers/JointTrajectoryController
    joints: arm_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_2_joint_effort_controller:
    type: effort_controllers/JointTrajectoryController
    joints: arm_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_3_joint_effort_controller:
    type: effort_controllers/JointTrajectoryController
    joints: arm_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_4_joint_effort_controller:
    type: effort_controllers/JointTrajectoryController
    joints: arm_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_5_joint_effort_controller:
    type: effort_controllers/JointTrajectoryController
    joints: arm_5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_6_joint_effort_controller:
    type: effort_controllers/JointTrajectoryController
    joints: arm_6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_left_joint_effort_controller:
    type: effort_controllers/JointTrajectoryController
    joints: wsg_50_base_joint_gripper_left
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_right_joint_effort_controller:
    type: effort_controllers/JointTrajectoryController
    joints: wsg_50_base_joint_gripper_right
    pid: {p: 100.0, i: 0.01, d: 10.0}
