robot:
  schunk_robot_arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint

    gains:
      arm_1_joint:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_2_joint:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_3_joint:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_4_joint:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_5_joint:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      arm_6_joint:  {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}


  wsg_gripper_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - wsg_50_finger_left_joint
      - wsg_50_finger_right_joint
    gains:
      wsg_50_finger_left_joint:   {p: 10.0, d: 3.0, i: 0.01}
      wsg_50_finger_right_joint:  {p: 10.0, d: 3.0, i: 0.01}
